### PR TITLE
The first pr for added first section of index.html

### PR DESCRIPTION
**Pull request by syam-ts**

### CODE REVIEW

**Comment by syam-ts** [comment]
Done from frontend

**Comment by syam-ts** [comment]
Done for css

**Comment by syam-ts** [comment]
Done for html

**Comment by syam-ts** [comment]
completed

**Review by syam-ts — COMMENTED** [review]
done

**Comment by syam-ts** [comment]
done

**Review by devss3 — COMMENTED** [review]
nice

**Comment by devss3** [comment]
s

**Comment by syam-ts** [comment]
er

**Review by syam-ts — COMMENTED** [review]
we

**Pull request closed without merging**
